// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BatchDownloadImages(arg1, arg2, arg3) {
  return window['go']['app']['App']['BatchDownloadImages'](arg1, arg2, arg3);
}

export function CancelImageDownload() {
  return window['go']['app']['App']['CancelImageDownload']();
}

export function CancelScheduledTask(arg1) {
  return window['go']['app']['App']['CancelScheduledTask'](arg1);
}

export function CancelScrape() {
  return window['go']['app']['App']['CancelScrape']();
}

export function CheckForUpdates() {
  return window['go']['app']['App']['CheckForUpdates']();
}

export function ClearAnalyticsCache() {
  return window['go']['app']['App']['ClearAnalyticsCache']();
}

export function ClearCache() {
  return window['go']['app']['App']['ClearCache']();
}

export function ClearExpiredCache() {
  return window['go']['app']['App']['ClearExpiredCache']();
}

export function ClearLoginCache() {
  return window['go']['app']['App']['ClearLoginCache']();
}

export function ClearLogs() {
  return window['go']['app']['App']['ClearLogs']();
}

export function ClearUpdateCache() {
  return window['go']['app']['App']['ClearUpdateCache']();
}

export function CreateScheduledTask(arg1) {
  return window['go']['app']['App']['CreateScheduledTask'](arg1);
}

export function DeleteDataFile(arg1) {
  return window['go']['app']['App']['DeleteDataFile'](arg1);
}

export function DeleteScheduledTask(arg1) {
  return window['go']['app']['App']['DeleteScheduledTask'](arg1);
}

export function ExportArticles(arg1, arg2, arg3) {
  return window['go']['app']['App']['ExportArticles'](arg1, arg2, arg3);
}

export function ExportCredentials() {
  return window['go']['app']['App']['ExportCredentials']();
}

export function ExportToJSON(arg1) {
  return window['go']['app']['App']['ExportToJSON'](arg1);
}

export function ExtractArticleImages(arg1) {
  return window['go']['app']['App']['ExtractArticleImages'](arg1);
}

export function ForceQuit() {
  return window['go']['app']['App']['ForceQuit']();
}

export function GetAllAccountNames() {
  return window['go']['app']['App']['GetAllAccountNames']();
}

export function GetAllLogs() {
  return window['go']['app']['App']['GetAllLogs']();
}

export function GetAnalyticsData(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['GetAnalyticsData'](arg1, arg2, arg3, arg4);
}

export function GetAppData() {
  return window['go']['app']['App']['GetAppData']();
}

export function GetAppVersion() {
  return window['go']['app']['App']['GetAppVersion']();
}

export function GetCacheStats() {
  return window['go']['app']['App']['GetCacheStats']();
}

export function GetCloseToTray() {
  return window['go']['app']['App']['GetCloseToTray']();
}

export function GetDataDirectory() {
  return window['go']['app']['App']['GetDataDirectory']();
}

export function GetDefaultConfig() {
  return window['go']['app']['App']['GetDefaultConfig']();
}

export function GetLoginStatus() {
  return window['go']['app']['App']['GetLoginStatus']();
}

export function GetRecentExecutionLogs(arg1) {
  return window['go']['app']['App']['GetRecentExecutionLogs'](arg1);
}

export function GetRecentLogs(arg1) {
  return window['go']['app']['App']['GetRecentLogs'](arg1);
}

export function GetRememberChoice() {
  return window['go']['app']['App']['GetRememberChoice']();
}

export function GetScheduledTask(arg1) {
  return window['go']['app']['App']['GetScheduledTask'](arg1);
}

export function GetTaskExecutionLogs(arg1, arg2) {
  return window['go']['app']['App']['GetTaskExecutionLogs'](arg1, arg2);
}

export function GetTimeInfo() {
  return window['go']['app']['App']['GetTimeInfo']();
}

export function GetUpdateIgnoredDate() {
  return window['go']['app']['App']['GetUpdateIgnoredDate']();
}

export function HideToTray() {
  return window['go']['app']['App']['HideToTray']();
}

export function ImportCredentials() {
  return window['go']['app']['App']['ImportCredentials']();
}

export function ImportJSONFile(arg1) {
  return window['go']['app']['App']['ImportJSONFile'](arg1);
}

export function IsAutostartEnabled() {
  return window['go']['app']['App']['IsAutostartEnabled']();
}

export function IsAutostartSilent() {
  return window['go']['app']['App']['IsAutostartSilent']();
}

export function ListDataFiles() {
  return window['go']['app']['App']['ListDataFiles']();
}

export function ListScheduledTasks(arg1) {
  return window['go']['app']['App']['ListScheduledTasks'](arg1);
}

export function LoadConfig() {
  return window['go']['app']['App']['LoadConfig']();
}

export function LoadDataFile(arg1) {
  return window['go']['app']['App']['LoadDataFile'](arg1);
}

export function Login() {
  return window['go']['app']['App']['Login']();
}

export function Logout() {
  return window['go']['app']['App']['Logout']();
}

export function OpenDataFileDialog() {
  return window['go']['app']['App']['OpenDataFileDialog']();
}

export function RunScheduledTaskNow(arg1) {
  return window['go']['app']['App']['RunScheduledTaskNow'](arg1);
}

export function SaveBase64File(arg1, arg2) {
  return window['go']['app']['App']['SaveBase64File'](arg1, arg2);
}

export function SaveConfig(arg1) {
  return window['go']['app']['App']['SaveConfig'](arg1);
}

export function SearchAccount(arg1) {
  return window['go']['app']['App']['SearchAccount'](arg1);
}

export function SelectDirectory() {
  return window['go']['app']['App']['SelectDirectory']();
}

export function SelectSaveFile(arg1, arg2) {
  return window['go']['app']['App']['SelectSaveFile'](arg1, arg2);
}

export function SetAutostart(arg1, arg2) {
  return window['go']['app']['App']['SetAutostart'](arg1, arg2);
}

export function SetCloseToTray(arg1) {
  return window['go']['app']['App']['SetCloseToTray'](arg1);
}

export function SetRememberChoice(arg1) {
  return window['go']['app']['App']['SetRememberChoice'](arg1);
}

export function SetUpdateIgnoredDate(arg1) {
  return window['go']['app']['App']['SetUpdateIgnoredDate'](arg1);
}

export function ShouldBlockClose() {
  return window['go']['app']['App']['ShouldBlockClose']();
}

export function ShowWindow() {
  return window['go']['app']['App']['ShowWindow']();
}

export function StartScrape(arg1) {
  return window['go']['app']['App']['StartScrape'](arg1);
}

export function Startup(arg1) {
  return window['go']['app']['App']['Startup'](arg1);
}

export function SyncTimeNow() {
  return window['go']['app']['App']['SyncTimeNow']();
}

export function UpdateAppData(arg1) {
  return window['go']['app']['App']['UpdateAppData'](arg1);
}

export function UpdateScheduledTask(arg1) {
  return window['go']['app']['App']['UpdateScheduledTask'](arg1);
}

export function ValidateCronExpression(arg1) {
  return window['go']['app']['App']['ValidateCronExpression'](arg1);
}
